<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="111" started-at="2018-12-15T21:58:34Z" finished-at="2018-12-15T21:58:34Z">
    <groups>
      <group name="Sanity">
        <method signature="Testing3.homeTest()[pri:1, instance:com.testing.Testing3@cb5822]" name="homeTest" class="com.testing.Testing3"/>
        <method signature="Testing3.mainTest()[pri:2, instance:com.testing.Testing3@cb5822]" name="mainTest" class="com.testing.Testing3"/>
      </group> <!-- Sanity -->
      <group name="Smoke">
        <method signature="Testing3.mainTest()[pri:2, instance:com.testing.Testing3@cb5822]" name="mainTest" class="com.testing.Testing3"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Default test" duration-ms="111" started-at="2018-12-15T21:58:34Z" finished-at="2018-12-15T21:58:34Z">
      <class name="com.testing.Testing3">
        <test-method status="PASS" signature="homeTest()[pri:1, instance:com.testing.Testing3@cb5822]" name="homeTest" duration-ms="23" started-at="2018-12-15T21:58:34Z" finished-at="2018-12-15T21:58:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeTest -->
        <test-method status="FAIL" signature="mainTest()[pri:2, instance:com.testing.Testing3@cb5822]" name="mainTest" duration-ms="6" started-at="2018-12-15T21:58:34Z" depends-on-methods="com.testing.Testing3.homeTest" finished-at="2018-12-15T21:58:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verifying element expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verifying element expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.testing.Testing3.mainTest(Testing3.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainTest -->
        <test-method status="SKIP" signature="endTest()[pri:3, instance:com.testing.Testing3@cb5822]" name="endTest" duration-ms="0" started-at="2018-12-15T21:58:34Z" depends-on-methods="com.testing.Testing3.mainTest" finished-at="2018-12-15T21:58:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing3.endTest()[pri:3, instance:com.testing.Testing3@cb5822] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing3.endTest()[pri:3, instance:com.testing.Testing3@cb5822] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.testing.Testing3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
